### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#1]
Esta buena la idea, pero como no estaba pensada faltó algo de dirección, 
sería ideal si fuese el logo de vía código y debajo dijese webshop.

No tengo ni idea de como hacer eso así que se lo pediré al diseñador

**Pedro debe pedirla al diseñador**

**Comment by markitos1990** [comment]
ESTA BIEN SOLO SE REMPLASARIA
