### ISSUE TITLE
Flechas del slider

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#10]
Como estas usando bootsratp, deberias usar fontawesome y hacer las flechas con

<i class="fas fa-angle-right fa-5x"></i>
<i class="fas fa-angle-left fa-5x"></i>

Hoy las use para otro carusel y las puse de rojo, las tuyas van bien de azul
![flechas](https://user-images.githubusercontent.com/3681300/47624507-7763d080-daeb-11e8-98ad-78ea97af9118.png)

**Comment by markitos1990** [comment]
listo

**Comment by ondoheer** [comment]
hermoso
