### ISSUE TITLE
Acordeon preguntas frecuentes

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#12]
poner el fondo del cuerpo del acordeon de blanco, así

![acordeon](https://user-images.githubusercontent.com/3681300/47624629-8303c700-daec-11e8-807e-236601bdb950.png)

**Comment by ondoheer** [comment]
Por cierto te felicito por usar acordeones

**Comment by markitos1990** [comment]
✌️ listo

**Comment by ondoheer** [comment]
hermoso, te felicito por poner cuestionarios mejores que lorem ipsum
