### ISSUE TITLE
Proyecto simple técnicas usadas

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#13]
Me parece que se pierden y son importantes, se me ocurren dos formas, en una lo creas como un cuadro, osea, una caja con fondo de color fijo y donde se note que es algo importante (usando los colres VC)

mira por ejemplo como aparece en el footer de las entrevistas del blog

https://blog.viacodigo.com/2018/08/30/mentor-entrevista-leonardo/

al final en la frase  "Si deseas formar parte de nuestra comunidad a través del programa de mentores de Vía Código, escríbenos a mentores@viacodigo.com"

**Comment by ondoheer** [comment]
![single-project](https://user-images.githubusercontent.com/3681300/47824832-ade45a00-dd3c-11e8-9653-c3b752c11dd0.png)

- [ ] Texto del articulo no debe estar justificado, los textos largos en web siempre alineados a la izq, un texto justificado al centro es dificil de leer
- [ ] Título en dos colores dentro de lo posible
- [ ] Tecnicas usadas está mucho mehjor así, pon la letra en blanco para que se vea más limpio.
- [ ] Imagen de web podria estar al mismo ancho que el texto, se le pone un alto máximo fijo y así no se ve tan alta y cuando abres con el lightbox (te felicito!!!) se ve toda puedes usar object-fit: cover para el img
- [ ] texto del artículo al menos en 18 a 20px en general.
- [ ] quizá técnicas se podría pulir como en esta sgte imágen, tiene vborde blanco de 2px y un contenedor que cubre todo. En el ejemplo se sube a la foto que no debería, es x q lo hice en el editor

![tecnicas](https://user-images.githubusercontent.com/3681300/47825131-39aab600-dd3e-11e8-9209-8b6a484ccc58.png)

**Comment by markitos1990** [comment]
ok

**Comment by ondoheer** [comment]
genial
