### ISSUE TITLE
Testimonios ajustes

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#15]
![testimonios](https://user-images.githubusercontent.com/3681300/47683821-c0289180-db9e-11e8-9aa2-6b3dbca4ccb1.png)

- [x] La rayita del slide seleccionado no debería crecwer, el cambio de color es suficiente, cuando crece se ve un poco roto

- [x] La palabra freelance no queda clara, parece un error que se quedó escrito, con via coder creo que todo bien. Quizá podrías poner el nombre en azul y el puesto (viacoder) en rojo?

- [x] El nombre de las personas debería ser más chico , ya que le quita protagonismo a la frase. amplía las columnas que ocupa todo y has crecer el texto de eso y reduce en del nombre. Piensalo así, que quiero que lean? Lo que dicen, luego viene el nombre.

**Comment by markitos1990** [comment]
ok

**Comment by ondoheer** [comment]
resuelto
