### ISSUE TITLE
Hero Image filtro

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#16]
Creo que necesitamos poner un div con opacity encima de la imágen para que se pueda leer el texto

![heroimage](https://user-images.githubusercontent.com/3681300/47684046-85732900-db9f-11e8-8cbc-ded774decb11.png)

Así como está no se lee ni eso ni el botón, prueba poner uno que cubra toda la imágen y otro que cubra solo lo del texto a ver cual se ve mejor.

mira por ejemplo en esta web pusimos una textura

https://andiamo.com.pe/

**Comment by ondoheer** [comment]
cambialo a rgba, cuando usas hex para canal alfa o transparencia, Visual Studio lo reconoce pero muchos navegadores no, no lo entienden

**Comment by markitos1990** [comment]
ESTA EN RGBA

**Comment by ondoheer** [comment]
Entonces es firefox que me lo cambiaba, escogiendo otra foto seguro se soluciona, lo damos por cerrado
