### ISSUE TITLE
calidad de los commits

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#17]
Con esto voy a ser pesado porque es loq ue distingue a  un buen programador de alguien que sabe pero parece flojo.

Tus textos de commits estan un poco vagos, no indican que has hecho. Este es un habito que los pro revisan siempre, y se que a veces da flojera, pero la flojera vale solo para tus proyectos personales :P

**Comment by markitos1990** [comment]
te refieres a los titulos al momento de salir, mejorare eso :/

**Comment by ondoheer** [comment]
exacto! de los titulos deberiamos poder entender que pasa, busca en google como hacer buenos commits de git

**Comment by ondoheer** [comment]
mejorando
