### ISSUE TITLE
Conseguir fotos de las webs para clientes

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#18]
Tengo que conseguir foto de las webs de :+1: 

- [x] Taller botanico
- [x] Colectivo oportunidad
- [x] Programa de inserción laboral
- [x] Charo Zapater
- [x] Via Codigo
- [x] Cultivando Salud

**Comment by markitos1990** [comment]
tu o yo??

**Comment by ondoheer** [comment]
yo por eso en personas asignadas pone mi nombre :D

**Comment by markitos1990** [comment]
ya los tienes

**Comment by ondoheer** [comment]
dos mas

![laboral](https://user-images.githubusercontent.com/3681300/48450207-6b2a7500-e773-11e8-805d-f530e444537f.png)
![cultivando](https://user-images.githubusercontent.com/3681300/48450210-6cf43880-e773-11e8-89f2-daca8647cc60.png)

**Comment by ondoheer** [comment]
Te los mandé al correo tmb. De ahí podrías descargarlo con el botón derecho
del mouse, guardar imágen como

**Comment by markitos1990** [comment]
falta uno :D

**Comment by ondoheer** [comment]
Si, hoy lo consigo, Antony estaba terminando

**Comment by ondoheer** [comment]
agrego charo

![charo-zapater](https://user-images.githubusercontent.com/3681300/48625530-87016700-e97d-11e8-8d0c-6ef90498a3e7.png)
