### ISSUE TITLE
Fotos debajo de la imagen grande en home

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#2]
No me queda claro que son y para que sirven

**Comment by markitos1990** [comment]
AHI IRAN LAS AGENCIAS NOTICIARIAS COMO ATV LA REPUBLICA. SOLO PUSE FOTOS PORQUE NO TENIA LOGOS O ICONOS DE NOTICIAS

**Comment by ondoheer** [comment]
no se si en git ya aprendiste branch (rama) si es así puedes ver en el proyecto anterior que estoy trabajando en un branch que se llama v3.0 dnd hay sección de noticias y ahí salen los logos de los 4 sitios, por ahora tenemos solo 4. 

sino te cuento, los logos son:

la replublica
correo
gestion
trome

y lleva cada uno a los articulos del blog de eso
https://blog.viacodigo.com/

de correo no hay x q nunca sacaron articulo online

**Comment by markitos1990** [comment]
no se donde se ubica me pasarias el link porfabor

**Comment by markitos1990** [comment]
y los logos

**Comment by ondoheer** [comment]
https://github.com/Via-Codigo/web-vc-ironman/tree/v3.0/images/logos  aqui estan los logos de esas cuatro publicaciones, entre otros, usa solo esos 4

**Comment by markitos1990** [comment]
listo solo el de la republica no me funciono, talvez este roto

**Comment by ondoheer** [comment]
No, es que el de la república  es un SVG que es blanco, quizá ese necita estar en negro, voy a ver si alguien lo puede convertir

**Comment by markitos1990** [comment]
si :v ya esta

**Comment by ondoheer** [comment]
hecho
