### ISSUE TITLE
Portafolio tamaño de textos

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#21]
En portafolio el texto de los proyectos es muy pequeño subelo de tamaño al mismo que le pongas a los cuerpos y puedes copiar el cuadrito de técnicas ahí tmb para rellenar, en esa parte solo habŕan una o dos líneas de texto

**Comment by ondoheer** [comment]
ya ví que si está debajo de la foto, cambialo a encima del texto que el orden sea:

Titulo del proyecto
tecnicas usadas
parrafo corto
link al proyecto completo

y al otro lado la foto

**Comment by markitos1990** [comment]
bn listo :v

**Comment by markitos1990** [comment]
si

**Comment by ondoheer** [comment]
Hecho
