### ISSUE TITLE
Titulos

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#22]
Los títulos en general se pierden y se ven muy chicos, intenta usar los mismos que en la web a ver que tal quedan, con la barrita roja al lado. Son los mensajes más importantes que tenemos, imagina que de esta web depende conseguirte más chamba

**Comment by ondoheer** [comment]
Mucho mejor, ahora hay que aumentar los márgenes para que se vean más limpios, ponles márgenes de 50 px arriba y abajo.

**Comment by markitos1990** [comment]
margen :v

**Comment by ondoheer** [comment]
listo
