### ISSUE TITLE
Animación incorrecta cuando se cambia tamaño de pantalla

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#24]
Cuando cambio de pantalla grande a chica se anima todo el slider el home, eso no debería pasar ya que alenta la experiencia de navegación

**Comment by markitos1990** [comment]
mm bno no pense que incomodaria :c

**Comment by ondoheer** [comment]
Porque le quita tiempo al usuario esperar a que eso se mueva. Los usuarios de internet promedio son muy flojos y si les quitas tiempo se van de la web.
