### ISSUE TITLE
Testimonios muy grandes

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#26]
En mobile los testimonios deben achicar su texto, están muy grandes y no se leen bien, hay que probar cambiarlos para cada tamaño que lo necesite

**Comment by markitos1990** [comment]
si listo creo que 18 estaria bn

**Comment by ondoheer** [comment]
He probado y con 16px queda mejor y bajarle el padding a 25px, 
```
blockquote {
    font-size: 16px;
}
blockquote {
    background-color: #DB532B;
    box-shadow: 0 5px 2px rgba(0,0,0,0.1);
    color: white;
    margin: 14px 0px;
    padding: 25px;
    position: relative;
    transition: background-color 0.6s linear;
    font-size: 24px;
}
```

**Comment by ondoheer** [comment]
No, ese es el código de tu css solonq no pude q línea.

El de arriba es el qnva dentro del media query.

El otro es el que tienes x defecto donde lo que cambie fue el padding.

Lo que pasa es que lo saque del inspector de Chrome y ahí no copia las
líneas

**Comment by markitos1990** [comment]
entendi :v jaja
