### ISSUE TITLE
Mejora de performance

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#30]
- [x] La línea al lado de los títulos no debería ser una imágen, sino un border o un before element, así la web carga más rápido x q no tiene que llamar a una imagen.

**Comment by markitos1990** [comment]
ok

**Comment by ondoheer** [comment]
Genialisimo, vez que bien se resuyelve solo con CSS? ahora habría que hacer lo mismo en la de VC :P
