### ISSUE TITLE
Agregar sección de contrátanos en todas las secciones

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#31]
Hay que agregar en todas las webs que no son contrátanos una sección debajo (antes del footer) que sea como esta:

![ejemplo](https://user-images.githubusercontent.com/3681300/48271244-eb667880-e409-11e8-8c74-25d5233cf0b9.png)

Pero que diga Contrátanos y que tenga el botón que hemos diseñado para el menú en contrátenos en el issue #32  vez de ese y te lleve a la página de contratar.

De esa forma siempre les facilitamos el contrararlos.

**Comment by markitos1990** [comment]
bn

**Comment by ondoheer** [comment]
Bien, solo asegurate de que la linea azul se va en hover (cuando corrijas el issue anterior)

**Comment by markitos1990** [comment]
listo

**Comment by ondoheer** [comment]
Último punto y disculpa que no lo pidiera antes, que las letras estén en mayúscula como en el de contratanos

**Comment by markitos1990** [comment]
Las mayusculas simbolisan mucho verdad

**Comment by ondoheer** [comment]
Las mayusculas, cognitivamente, dan más fuerza a mensajes cortos, si pones todo en mayusculas el cerebro también se confunde, pero en botones simples como este, ayudan muchísimo!
