### ISSUE TITLE
Crear botón de contrátenos y usarlo en el menú 

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#32]
![boton](https://user-images.githubusercontent.com/3681300/48271475-69c31a80-e40a-11e8-80c6-911ca09d295d.png)

- [x] Moverlo a tercer lugar en el menú
- [x] Agregarlo a todas las páginas
- [x] Debería ser una clase que le agregas a un a y lo convierte en esto
- [x] En hover el background cambia al amarillo

Estos son los estilos que use

```
element {
    background-color: #f05351;
    color: white;
    line-height: 40px;
    padding: 0 20px;
    border-radius: 3px;
}
```

**Comment by markitos1990** [comment]
:v bn

**Comment by ondoheer** [comment]
* quitar la línea que aparece en hover (la azul) ensucia y no deja que se lea.

Te explico x q solo este botón así.

En diseño existe lo que se llama "Call to action" o llamado a la acción. Son aquellos links que tu **quieres** que el user use ya que de esto trata tu negocio. Destacamos solo este porque así el ojo y el cerebro lo ven como más importante y te jala a darle click.

**Comment by markitos1990** [comment]
ya lo saque

**Comment by ondoheer** [comment]
perfecto
