### ISSUE TITLE
Crear páginas para proyectos unicos

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#33]
Crear html para cada proyecto, ponienso el título y la imágen de cada uno (la técnica y el texto lo escribo yo cuando esten)  Y vincularlas desde la página de proyectos o el slider

- [x] taller-botanico.html
- [x] cultivando-salud.html
- [x] via-codigo.html
- [x] charo-zapater.html
- [x] programa-reinsercion-laboral.html
- [x] colectivo-oportunidad-cambio.html

Con este cerramos!

**Comment by markitos1990** [comment]
IMAGEN DE ZAPATER FALTA :V

**Comment by ondoheer** [comment]
Los nombres de los archivos deben ser los que te pedí. Estos nombres ayudan a que google entienda mejor de que se tratan y beneficia a la web. Es parted e un conocimiento que se llama SEO (optimización para motores de búsqueda).

Si te das cuenta, por ejemplo, uso "-" en vez de "_" eso es x q google entiende "-" como separador de palabras y "_" como parte de la misma palabra.

**Comment by markitos1990** [comment]
listo

**Comment by ondoheer** [comment]
Listo
