### ISSUE TITLE
Redactar Contenidos Single Project

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#36]
Hay que redactar contenidos para cada proyecto que expliquen que necesitó el cliente y que se hizo

- [x] Taller botánico
- [x] Vía Código
- [x] Charo Zapater
- [x] Reinserción Laboral
- [x] Colectivo Oportunidad
- [x] Cultivando Salud

**Comment by ondoheer** [comment]
Charo Zapater

Charo Zapater es una reconocida artista plástica. Necesitaba renovar su web con urgencia. Su web anterior estaba construida en **flash**, y desde hace varios años que muchos navgeadores, y ningún celular, pueden ver este tipo de webs. El mundo se estaba perdiendo conocer su obra!

Con Charo buscamos un diseño más adecuado a los estilos gráficos actuales, que aprovechase el tamaño de las pantallas actuales para lucir su obra. 

En vez de trabajar con plantillas, decidimos construir desde cero, ya que así podíamos acelerar la velocidad de carga en una web ya cargada de imágenes.

Trabajamos en conjunto con nuestros aliados para crear un backend en Drupal que permitiese a Charo mantener su web actualizada cuando quisiera sin necesitar de la ayuda de un equipo de programadores.

Estamos muy orgullosos de este trabajo!

**Comment by ondoheer** [comment]
Reinserción Laboral

Este fue uno de los proyectos finales que hicimos los de la primera promoción. Cuando nos preguntaron que web querríamos construir, todos pensamos en formas de contar al mundo, que en Maranguita también suceden cosas buenas, que no todo son motines, y que lo que cuentan fuera de nosotros es muy poco.

Nuestro equipo decidió trabajar una web para el área de Reinseción Social y Laboral del Centro. Queremos que fuera sepan que hay empresas que brindan su apoyo a algunos de nosootros, y que salimos a trabajar y a aprender a ser ciudadanos provechosos. Queremos que otras empresas que quieran apoyarnos también se animen a participar, y que la gente que quiere saber más, pueda leer los testimonios de las personas que han cambiado su vida gracias al apoyo de gente y empresas que creen en nuestro futuro.

Para esta web modificamos una plantilla y creamos nuevos componentes para poder aprovechar los contenidos que teníamos disponibles.

**Comment by ondoheer** [comment]
Colectivo Oportunidad

Este fue un trabajo final de la primera promoción. Como equipo quisimos apoyar al Colectivo. El Colectivo está conformado por varias de las instituciones que trabajan en Maranguita con proyectos y talleres para ayudarnos. Queríamos que tuvieran un sitio donde contar sus historias, los éxitos que tenemos juntos, y donde la gente pueda ver todas las cosas que hacemos aquí dentro!

La web fue construida desde cero, nosotros nos encargamos del diseño, tanto de la marca como de la web (buscamos referentes). El backend está hecho en WordPress y lo hicieron nuestros aliados programadores.

Si tienes un proyecto parecido, búscanos!

**Comment by kullawa** [comment]
Cultivando Salud

Este fue un trabajo final de la primera promoción. Un eje fundamental en el aprendizaje en Vía Código es en el crecimiento personal de los adolescentes. Por eso, decidimos apoyar al proyecto Cultivando Salud que aporta una mirada integral de la salud personas, desde el cuidado de su salud mental, lo cual iba de la mano con el aprendizaje de los Via Coders.

Cultivando Salud es una iniciativa que difundía su trabajo en redes sociales; sin embargo no contaba con una página web, y es ahí donde decimos utilizar todo lo aprendido en HTML y CSS a lo largo del año para aportar a este proyecto.

Estamos muy contentos de sumarnos a estas iniciativas!
