### ISSUE TITLE
Nuevos Testimonios

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#41]
Debe crearse al menos 3 nuevos testimonios 
con los participantes actuales del webshop

Hay que decidir si reemplazamos los que hay o se ponen más

**Comment by David-Csc** [comment]
Requiero que me escriban sus testimonios mis colegas @poma-13  @fernando-cv @OsaeiPT  , porfavor mandenme los testimoios urgente.

**Comment by OsaeiPT** [comment]
Ser Un Via Coder Era Una De Mis Metas y Lo Cumpli Y Ahora Estoy Trabajando y Sustentandome Economicamente
