### ISSUE TITLE
Portafolio de la web de Meche

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#42]
- [x] Hay que crear la pagina simgle de meche
- [x] hay que crear la web de meche dentro de portafolio
- [x] hay que crear la web de meche dentro de home

**Comment by fernando-cv** [comment]
necesito las fotos

**Comment by fernando-cv** [comment]
tambien los textos :D

**Comment by ondoheer** [comment]
![ma](https://user-images.githubusercontent.com/3681300/64723470-39b72e80-d496-11e9-8fd7-5041beefddd2.png)
![ma-400](https://user-images.githubusercontent.com/3681300/64723471-39b72e80-d496-11e9-9092-4bb9bc7a6320.png)
![ma-700](https://user-images.githubusercontent.com/3681300/64723472-3a4fc500-d496-11e9-8ae1-f457c747fb4c.png)

**Comment by ondoheer** [comment]
Tienes que decirme que textos necesitas, pásame uno de ejemplo de lo que quieres

**Comment by fernando-cv** [comment]
texto del index y parrafo

**Comment by ondoheer** [comment]
Mercedes Araoz nos visitó en el 2018 en el CJDRL y al ver la calidad de trabajo que ofrecíamos desde allí, decidió encargarnos este proyecto. Creemos que es nuestro proyecto bandera, ya que hemos acompañado a la Vicepresidenta desde la concepción de la idea, desarrollo de la arquitectura, creación de una guía de stilos y programada con un sistema de componentes. 
Sabemos que esta web le servirá de plataforma para poder comunicarse de forma efectiva con los peruanos, brindando así un aún mejor servicio a la ciudadanía.

**Comment by fernando-cv** [comment]
ya esta :D

**Comment by ondoheer** [comment]
Lo reviso y te aviso cuando este
