### ISSUE TITLE
Portafolio web candelaria

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#43]
- [ ] Hay que crear la pagina simgle de candelaria
- [ ] hay que crear la web de candelaria dentro de portafolio
- [ ] hay que crear la web de candelaria dentro de home

**Comment by OsaeiPT** [comment]
Pedro Necesito la imagen de candelaria

**Comment by ondoheer** [comment]
![candelaria-400](https://user-images.githubusercontent.com/3681300/64718122-35394880-d48b-11e9-8245-1d94006c51f2.png)
![candelaria-700](https://user-images.githubusercontent.com/3681300/64718123-35394880-d48b-11e9-98f5-3dd968d9acf5.png)
![candelaria](https://user-images.githubusercontent.com/3681300/64718125-35394880-d48b-11e9-8cbc-90d52fb34557.png)

@OsaeiPT aquí estan

**Comment by OsaeiPT** [comment]
Pedro mandame el texto por favor

**Comment by ondoheer** [comment]
La web de candelaria necesitaba una nueva imagen que reflejase el estado actual de la marca. Trabajamos mano a mano con el equipo de diseño de marca de Candelaria para crear una experiencia a la medida. Como parte del proyecto hicimos asesoría de diseño, arquitectura y estrategia comercial. La web cuenta además con un sistema CMS a la medida creado en Drupal.
