### ISSUE TITLE
Portafolio web vicuña

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#44]
- [ ] Hay que crear la pagina simgle de vicuña
- [ ] hay que crear la web de vicuña dentro de portafolio
- [ ] hay que crear la web de vicuña dentro de home

**Comment by poma-13** [comment]
pedro porfavor pasame las imagenes de la pagina vicuña

**Comment by ondoheer** [comment]
![vicuna](https://user-images.githubusercontent.com/3681300/64723372-096f9000-d496-11e9-8e15-11b378f50305.png)
![vicuna-400](https://user-images.githubusercontent.com/3681300/64723374-096f9000-d496-11e9-9dea-dd729ee43a28.png)
![vicuna-700](https://user-images.githubusercontent.com/3681300/64723376-096f9000-d496-11e9-8b52-6e65523ff0d8.png)

**Comment by ondoheer** [comment]
texto para la web


Cervecería Candelaria nos contactó para desarrollar su página principal, y al ver la calidad de nuestro trabajo nos pidió que le ayudásemos a realizar ajustes en la web de Vicuña, su marca premium. 
Trabajamos con su equipo para definir que soluciones inmediatas le ofreceríamos, y cuales se dejarán para la versión 2 de la web.
