### ISSUE TITLE
Página de portafolio de proyectos

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/vc-webshop#7]
NO usar slider, deben verse todos hacia abajo intercalando izq y derecha las imágenes, sino se ve muy vacía y los sliders no son útiles cuando hay muchas cosas

**Comment by markitos1990** [comment]
si eso estab en dudad, bueno solo quitarle el slider

**Comment by ondoheer** [comment]
hecho, prueba poniendo fotos de webs, ya que eso es lo que se mostrará

**Comment by ondoheer** [comment]
mejor, a ver saca las de la web de athelas.pe

**Comment by ondoheer** [comment]
bien

**Comment by ondoheer** [comment]
En esta parte poque no pones la cajita azul de tecnicas usadas tmb?

**Comment by markitos1990** [comment]
si verdad listo :v

**Comment by ondoheer** [comment]
Muy paja
